script:
  - "npm run travis"

language: node_js

node_js:
  - "6"
  - "8"
  - "10"

branches:
  only:
    - master
    - dev

matrix:
  fast_finish: true
  include:
    - node_js: "10"
      env: COVERAGE=true
  allow_failures:
    - env: COVERAGE=true

sudo: false
